insert into public.exercises (
  name,
  slug,
  muscle_group,
  primary_muscle,
  secondary_muscles,
  equipment,
  category,
  tracking_type,
  aliases,
  source,
  is_custom
)
values
  ('Abdominal Bicicleta', 'abdominal-bicicleta', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto', 'abdominal-corto', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto (Con Peso Añadido)', 'abdominal-corto-con-peso-anadido', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto (Máquina)', 'abdominal-corto-maquina', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto con Cable', 'abdominal-corto-con-cable', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto en Banco Inclinado', 'abdominal-corto-en-banco-inclinado', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Banco', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominal Corto en Banco Inclinado (Con Peso Añadido)', 'abdominal-corto-en-banco-inclinado-con-peso-anadido', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominales Bicicleta Piernas Levantadas', 'abdominales-bicicleta-piernas-levantadas', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominales Cortos Oblicuos', 'abdominales-cortos-oblicuos', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominales en V', 'abdominales-en-v', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominales Tijera', 'abdominales-tijera', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abdominales Toque al Talón', 'abdominales-toque-al-talon', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Abducción de Caderas', 'abduccion-de-caderas', 'Abductores', 'Abductores', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aducción de Caderas', 'aduccion-de-caderas', 'Aductores', 'Aductores', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aerobics', 'aerobics', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aleteo de Piernas', 'aleteo-de-piernas', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Almeja', 'almeja', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Alrededor del Mundo', 'alrededor-del-mundo', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Apertura Declinada (Mancuerna)', 'apertura-declinada-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aperturas (Banda)', 'aperturas-banda', 'Pecho', 'Pecho', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aperturas (Mancuerna)', 'aperturas-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aperturas (Máquina)', 'aperturas-maquina', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aperturas de Pecho Sentado (Cable)', 'aperturas-de-pecho-sentado-cable', 'Pecho', 'Pecho', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Aperturas Inclinadas (Mancuerna)', 'aperturas-inclinadas-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Arnold Press (Mancuerna)', 'arnold-press-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Arrancada con Mancuerna', 'arrancada-con-mancuerna', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Arrancada con Pesa Rusa', 'arrancada-con-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Ball Slams', 'ball-slams', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Balón medicinal', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Band Pullaparts', 'band-pullaparts', 'Hombros', 'Hombros', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Behind the Back Curl (Cable)', 'behind-the-back-curl-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Belt Squat (Machine)', 'belt-squat-machine', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Bicicleta', 'bicicleta', 'Cardio', 'Cardio', ARRAY[]::text[], 'Bicicleta', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Bicicleta de Aire', 'bicicleta-de-aire', 'Cardio', 'Cardio', ARRAY[]::text[], 'Bicicleta', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Boxeo', 'boxeo', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Buen Día (Barra)', 'buen-dia-barra', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Burpee', 'burpee', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Burpee Sobre la Barra', 'burpee-sobre-la-barra', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cable Core Palloff Press', 'cable-core-palloff-press', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cable Twist (Down to up)', 'cable-twist-down-to-up', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cable Twist (Up to down)', 'cable-twist-up-to-down', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cables Cruzados', 'cables-cruzados', 'Pecho', 'Pecho', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cables Cruzados Bajos', 'cables-cruzados-bajos', 'Pecho', 'Pecho', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cables Cruzados de Un Solo Brazo', 'cables-cruzados-de-un-solo-brazo', 'Pecho', 'Pecho', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Calentamiento', 'calentamiento', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Caminar', 'caminar', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Caminata Lateral con Banda Elástica', 'caminata-lateral-con-banda-elastica', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cargada con Pesa Rusa', 'cargada-con-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cargada y Press', 'cargada-y-press', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cargada y Tirón', 'cargada-y-tiron', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Chest Fly (Suspension)', 'chest-fly-suspension', 'Pecho', 'Pecho', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cinta', 'cinta', 'Cardio', 'Cardio', ARRAY[]::text[], 'Cinta', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Clean', 'clean', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Clean and Jerk', 'clean-and-jerk', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Correr', 'correr', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Crunch Inverso', 'crunch-inverso', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Cuerdas de Batalla', 'cuerdas-de-batalla', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl a un Brazo (Cable)', 'curl-a-un-brazo-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Araña (Barra)', 'curl-arana-barra', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Araña (Mancuerna)', 'curl-arana-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl con Barra EZ', 'curl-con-barra-ez', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl con Pesa Rusa', 'curl-con-pesa-rusa', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps (Barra)', 'curl-de-biceps-barra', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps (Cable)', 'curl-de-biceps-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps (Mancuerna)', 'curl-de-biceps-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps (Máquina)', 'curl-de-biceps-maquina', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps (Suspensión)', 'curl-de-biceps-suspension', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Biceps 21', 'curl-de-biceps-21', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps con Cable', 'curl-de-biceps-con-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps Detrás de Espalda (Barra)', 'curl-de-biceps-detras-de-espalda-barra', 'Antebrazos', 'Antebrazos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Bíceps Inclinado (Mancuerna)', 'curl-de-biceps-inclinado-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Concentración Invertido', 'curl-de-concentracion-invertido', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Extensión de Muñeca (Barra)', 'curl-de-extension-de-muneca-barra', 'Antebrazos', 'Antebrazos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Martillo Cruzado', 'curl-de-martillo-cruzado', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Muñeca Palmas arriba', 'curl-de-muneca-palmas-arriba', 'Antebrazos', 'Antebrazos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Pierna Sentado', 'curl-de-pierna-sentado', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl de Piernas Acostado (Máquina)', 'curl-de-piernas-acostado-maquina', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Invertido (Barra)', 'curl-invertido-barra', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Invertido (Cable)', 'curl-invertido-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Invertido (Mancuerna)', 'curl-invertido-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Martillo (Banda)', 'curl-martillo-banda', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Martillo (Cable)', 'curl-martillo-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Martillo (Mancuerna)', 'curl-martillo-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Sobre Cabeza (Cable)', 'curl-sobre-cabeza-cable', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curl Zottman (Mancuerna)', 'curl-zottman-mancuerna', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curls de Concentración', 'curls-de-concentracion', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curls de Piernas de Pie', 'curls-de-piernas-de-pie', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curls Nórdicos de Isquiotibiales', 'curls-nordicos-de-isquiotibiales', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Curva Lateral (Mancuerna)', 'curva-lateral-mancuerna', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dead Bug', 'dead-bug', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dead Hang', 'dead-hang', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada', 'dominada', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada (Asistida)', 'dominada-asistida', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada (Banda)', 'dominada-banda', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada (Con Peso Añadido)', 'dominada-con-peso-anadido', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada Abierta', 'dominada-abierta', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada Negativa', 'dominada-negativa', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominada Perfecta (Gironda)', 'dominada-perfecta-gironda', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominadas Chin Up', 'dominadas-chin-up', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominadas Chin Up (Asistida)', 'dominadas-chin-up-asistida', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominadas Chin Up (Con Peso)', 'dominadas-chin-up-con-peso', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominadas con Kipping', 'dominadas-con-kipping', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dominadas Escapulares', 'dominadas-escapulares', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Drag Curl', 'drag-curl', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dragon Flag', 'dragon-flag', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dragonfly', 'dragonfly', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Dumbbell Squeeze Press', 'dumbbell-squeeze-press', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Cadera a Una Pierna', 'elevacion-de-cadera-a-una-pierna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos a Una Pierna', 'elevacion-de-gemelos-a-una-pierna', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos a Una Pierna (Barra)', 'elevacion-de-gemelos-a-una-pierna-barra', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos a Una Pierna (Macuerna)', 'elevacion-de-gemelos-a-una-pierna-macuerna', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos a Una Pierna (Máquina)', 'elevacion-de-gemelos-a-una-pierna-maquina', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos de Pie', 'elevacion-de-gemelos-de-pie', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos de Pie (Barra)', 'elevacion-de-gemelos-de-pie-barra', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos de Pie (Mancuerna)', 'elevacion-de-gemelos-de-pie-mancuerna', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos de Pie (Máquina)', 'elevacion-de-gemelos-de-pie-maquina', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos de Pie (Smith)', 'elevacion-de-gemelos-de-pie-smith', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Gemelos Sentado', 'elevacion-de-gemelos-sentado', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación de Rodillas', 'elevacion-de-rodillas', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación en Y con Soporte en el Pecho (Mancuerna)', 'elevacion-en-y-con-soporte-en-el-pecho-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Frontal (Banda)', 'elevacion-frontal-banda', 'Hombros', 'Hombros', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Frontal (Barra)', 'elevacion-frontal-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Frontal (Cable)', 'elevacion-frontal-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Frontal (Mancuerna)', 'elevacion-frontal-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación Frontal (Suspensión)', 'elevacion-frontal-suspension', 'Hombros', 'Hombros', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación Frontal con Disco', 'elevacion-frontal-con-disco', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevación Lateral a un Brazo (Cable)', 'elevacion-lateral-a-un-brazo-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Laterales (Banda)', 'elevacion-laterales-banda', 'Hombros', 'Hombros', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Laterales (Cable)', 'elevacion-laterales-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Laterales (Mancuerna)', 'elevacion-laterales-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevacion Laterales (Máquina)', 'elevacion-laterales-maquina', 'Hombros', 'Hombros', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Elevaciones Laterales de Pierna', 'elevaciones-laterales-de-pierna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Empuje de Caderas', 'empuje-de-caderas', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Empuje de Caderas (Barra)', 'empuje-de-caderas-barra', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Empuje de Fuerza', 'empuje-de-fuerza', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Empuje de Trineo', 'empuje-de-trineo', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimiento de Hombros (Barra)', 'encogimiento-de-hombros-barra', 'Trapecio', 'Trapecio', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimiento de Hombros (Cable)', 'encogimiento-de-hombros-cable', 'Trapecio', 'Trapecio', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimiento de Hombros (Mancuerna)', 'encogimiento-de-hombros-mancuerna', 'Trapecio', 'Trapecio', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimiento de Hombros (Máquina Smith)', 'encogimiento-de-hombros-maquina-smith', 'Trapecio', 'Trapecio', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimiento de Hombros con Salto', 'encogimiento-de-hombros-con-salto', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Encogimientos (Máquina)', 'encogimientos-maquina', 'Trapecio', 'Trapecio', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Entrenador Elíptico', 'entrenador-eliptico', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Equilibrio Invertido', 'equilibrio-invertido', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Escalada', 'escalada', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Escaladores', 'escaladores', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Esquí', 'esqui', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Estiramiento', 'estiramiento', 'Otro', 'Otro', ARRAY[]::text[], 'Peso corporal', 'stretching', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Estocada con Mancuerna Sobre Cabeza', 'estocada-con-mancuerna-sobre-cabeza', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Estocada con Salto', 'estocada-con-salto', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Cuello Acostado', 'extension-de-cuello-acostado', 'Cuello', 'Cuello', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Cuello Acostado (Con Peso)', 'extension-de-cuello-acostado-con-peso', 'Cuello', 'Cuello', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Espalda (Hiperextensión con peso)', 'extension-de-espalda-hiperextension-con-peso', 'Espalda baja', 'Espalda baja', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Espalda (Hiperextensión)', 'extension-de-espalda-hiperextension', 'Espalda baja', 'Espalda baja', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Espalda (Máquina)', 'extension-de-espalda-maquina', 'Espalda baja', 'Espalda baja', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extension de Pantorrilla (Máquina)', 'extension-de-pantorrilla-maquina', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Pierna', 'extension-de-pierna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps (Barra)', 'extension-de-triceps-barra', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps (Cable)', 'extension-de-triceps-cable', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps (Mancuerna)', 'extension-de-triceps-mancuerna', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps (Máquina)', 'extension-de-triceps-maquina', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps a un Brazo (Cable)', 'extension-de-triceps-a-un-brazo-cable', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps Atrás (Cable)', 'extension-de-triceps-atras-cable', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión de Tríceps de un Brazo (Mancuerna)', 'extension-de-triceps-de-un-brazo-mancuerna', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensión Tríceps (Suspensión)', 'extension-triceps-suspension', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Extensiones a Una Pierna', 'extensiones-a-una-pierna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Feet Up Bench Press (Barbell)', 'feet-up-bench-press-barbell', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexión a Una Mano', 'flexion-a-una-mano', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexión de Brazos Tocando Hombro', 'flexion-de-brazos-tocando-hombro', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexión Declinada', 'flexion-declinada', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexión en Pica', 'flexion-en-pica', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexión Lateral', 'flexion-lateral', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones', 'flexiones', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones (Agarre Cerrado)', 'flexiones-agarre-cerrado', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones con Palmada', 'flexiones-con-palmada', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones de Brazos (Con Peso Agregado)', 'flexiones-de-brazos-con-peso-agregado', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones de Cuello Acostado', 'flexiones-de-cuello-acostado', 'Cuello', 'Cuello', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones de Cuello Acostado (Con Peso)', 'flexiones-de-cuello-acostado-con-peso', 'Cuello', 'Cuello', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones de Rodillas', 'flexiones-de-rodillas', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones Diamante', 'flexiones-diamante', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones en Plancha', 'flexiones-en-plancha', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'time', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones Inclinadas', 'flexiones-inclinadas', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Flexiones Verticales', 'flexiones-verticales', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondo de Tríceps', 'fondo-de-triceps', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondo de Tríceps (Asistido)', 'fondo-de-triceps-asistido', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondo de Tríceps (Con Peso Añadido)', 'fondo-de-triceps-con-peso-anadido', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos', 'fondos', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos (Asistidos)', 'fondos-asistidos', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos (Con Peso Añadido)', 'fondos-con-peso-anadido', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos de Tríceps en Suelo', 'fondos-de-triceps-en-suelo', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos en Anillas', 'fondos-en-anillas', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Fondos en Banco', 'fondos-en-banco', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Banco', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Frog Pumps (Mancuerna)', 'frog-pumps-mancuerna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Front Lever Elevación', 'front-lever-elevacion', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Front Lever Sostenida', 'front-lever-sostenida', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Glute Ham Raise', 'glute-ham-raise', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Hang Clean', 'hang-clean', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Hang Snatch', 'hang-snatch', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('HIIT', 'hiit', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Hip Thrust (Smith Machine)', 'hip-thrust-smith-machine', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Hiperextensión Inversa', 'hiperextension-inversa', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Hollow Rock', 'hollow-rock', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'time', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Impulso de Cadera (Máquina)', 'impulso-de-cadera-maquina', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Impulso de Cadera a una Pierna (Mancuerna)', 'impulso-de-cadera-a-una-pierna-mancuerna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jack Knife (Suspensión)', 'jack-knife-suspension', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón al Pecho - Agarre Cerrado (Cable)', 'jalon-al-pecho-agarre-cerrado-cable', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón al Pecho (Banda)', 'jalon-al-pecho-banda', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón al Pecho (Cable)', 'jalon-al-pecho-cable', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón al Pecho (Máquina)', 'jalon-al-pecho-maquina', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón al Pecho a Un Brazo', 'jalon-al-pecho-a-un-brazo', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón de Remo a Un Brazo', 'jalon-de-remo-a-un-brazo', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jalón de Rodillas (banda)', 'jalon-de-rodillas-banda', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Jumping Jack', 'jumping-jack', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Kettlebell Around the World', 'kettlebell-around-the-world', 'Hombros', 'Hombros', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Kettlebell Halo', 'kettlebell-halo', 'Hombros', 'Hombros', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('L-Sit Sostenido', 'l-sit-sostenido', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Landmine 180', 'landmine-180', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Landmine Press a Un Brazo (Barra)', 'landmine-press-a-un-brazo-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Landmine Sentadilla y Press', 'landmine-sentadilla-y-press', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Lanzamientos de Balón', 'lanzamientos-de-balon', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Balón medicinal', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Levantamiento de Piernas en Barra', 'levantamiento-de-piernas-en-barra', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Levantamiento de Piernas Tumbado', 'levantamiento-de-piernas-tumbado', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Levantamiento de Rodillas en Barra', 'levantamiento-de-rodillas-en-barra', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Levantamiento de Rodillas Tumbado', 'levantamiento-de-rodillas-tumbado', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Levantamiento Turco con Pesa Rusa', 'levantamiento-turco-con-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Máquina de Remo', 'maquina-de-remo', 'Cardio', 'Cardio', ARRAY[]::text[], 'Máquina', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Máquina Escaladora', 'maquina-escaladora', 'Cardio', 'Cardio', ARRAY[]::text[], 'Máquina', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Máquina para Fondos Sentado', 'maquina-para-fondos-sentado', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Mariposa (Pec Deck)', 'mariposa-pec-deck', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Muscle Up', 'muscle-up', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Natación', 'natacion', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Overhead Plate Raise', 'overhead-plate-raise', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Overhead Triceps Extension (Cable)', 'overhead-triceps-extension-cable', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Partial Glute Bridge (Barbell)', 'partial-glute-bridge-barbell', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Paseo del Granjero', 'paseo-del-granjero', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patada de Burro', 'patada-de-burro', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patada de Burro (Máquina)', 'patada-de-burro-maquina', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patada de Glúteo con Cable', 'patada-de-gluteo-con-cable', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patada de Tríceps', 'patada-de-triceps', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patadas Boca de Incendio', 'patadas-boca-de-incendio', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Patinaje', 'patinaje', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Perro de Caza', 'perro-de-caza', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto (Banda)', 'peso-muerto-banda', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto (Barra Trap)', 'peso-muerto-barra-trap', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto (Barra)', 'peso-muerto-barra', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto (Mancuerna)', 'peso-muerto-mancuerna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto (Máquina Smith)', 'peso-muerto-maquina-smith', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto con Tirón Alto', 'peso-muerto-con-tiron-alto', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Piernas Estiradas', 'peso-muerto-piernas-estiradas', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Rumano (Barra)', 'peso-muerto-rumano-barra', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Rumano (Mancuerna)', 'peso-muerto-rumano-mancuerna', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Rumano a Una Pierna (Barra)', 'peso-muerto-rumano-a-una-pierna-barra', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Rumano a Una Pierna (Mancuerna)', 'peso-muerto-rumano-a-una-pierna-mancuerna', 'Isquiotibiales', 'Isquiotibiales', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Peso Muerto Sumo', 'peso-muerto-sumo', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pies a Barra', 'pies-a-barra', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pies a la Barra', 'pies-a-la-barra', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pilates', 'pilates', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pinwheel Curl (Dumbbell)', 'pinwheel-curl-dumbbell', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plancha', 'plancha', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'time', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plancha Inversa', 'plancha-inversa', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'time', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plancha Lateral', 'plancha-lateral', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'time', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plate Curl', 'plate-curl', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plate Press', 'plate-press', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Plate Squeeze (Svend Press)', 'plate-squeeze-svend-press', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Postura del Perro Cabeza Abajo', 'postura-del-perro-cabeza-abajo', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Power Clean', 'power-clean', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Power Snatch', 'power-snatch', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Preacher Curl (Barbell)', 'preacher-curl-barbell', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Preacher Curl (Dumbbell)', 'preacher-curl-dumbbell', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Preacher Curl (Machine)', 'preacher-curl-machine', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press a Una Pierna', 'press-a-una-pierna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca - Agarre Abierto (Barra)', 'press-de-banca-agarre-abierto-barra', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca - Agarre Cerrado (Barra)', 'press-de-banca-agarre-cerrado-barra', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca (Barra)', 'press-de-banca-barra', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca (Cable)', 'press-de-banca-cable', 'Pecho', 'Pecho', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca (Mancuerna)', 'press-de-banca-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca (Máquina Smith)', 'press-de-banca-maquina-smith', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca en Declive (Barra)', 'press-de-banca-en-declive-barra', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca en Declive (Mancuerna)', 'press-de-banca-en-declive-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca en Declive (Máquina Smith)', 'press-de-banca-en-declive-maquina-smith', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca en Declive (Máquina)', 'press-de-banca-en-declive-maquina', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca Inclinado (Barra)', 'press-de-banca-inclinado-barra', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca Inclinado (Mancuerna)', 'press-de-banca-inclinado-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Banca Inclinado (Máquina Smith)', 'press-de-banca-inclinado-maquina-smith', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros (Barra)', 'press-de-hombros-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros (Mancuerna)', 'press-de-hombros-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros (Máquina de Placas)', 'press-de-hombros-maquina-de-placas', 'Hombros', 'Hombros', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros (Máquina Smith)', 'press-de-hombros-maquina-smith', 'Hombros', 'Hombros', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros con Pesa Rusa', 'press-de-hombros-con-pesa-rusa', 'Hombros', 'Hombros', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros Sentado (Barra)', 'press-de-hombros-sentado-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros Sentado (Cable)', 'press-de-hombros-sentado-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros Sentado (Mancuerna)', 'press-de-hombros-sentado-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Hombros Sentado (Máquina)', 'press-de-hombros-sentado-maquina', 'Hombros', 'Hombros', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Pantorrilla (Máquina)', 'press-de-pantorrilla-maquina', 'Gemelos', 'Gemelos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Pecho (Banda)', 'press-de-pecho-banda', 'Pecho', 'Pecho', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Pecho (Máquina)', 'press-de-pecho-maquina', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Pecho Inclinado (Máquina)', 'press-de-pecho-inclinado-maquina', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Pecho Iso-Lateral (Máquina)', 'press-de-pecho-iso-lateral-maquina', 'Pecho', 'Pecho', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Piernas', 'press-de-piernas', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Piernas Sentado', 'press-de-piernas-sentado', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press de Suelo (Barra)', 'press-de-suelo-barra', 'Pecho', 'Pecho', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press en el Suelo (Mancuerna)', 'press-en-el-suelo-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press Francés (Barra)', 'press-frances-barra', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press Francés (Mancuerna)', 'press-frances-mancuerna', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press Hexagonal (Mancuerna)', 'press-hexagonal-mancuerna', 'Pecho', 'Pecho', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press JM (Barra)', 'press-jm-barra', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press Militar de Pie (Barra)', 'press-militar-de-pie-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Press Under', 'press-under', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Puente de Glúteos', 'puente-de-gluteos', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Puente de Glúteos con Una Pierna', 'puente-de-gluteos-con-una-pierna', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pull Over', 'pull-over', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pulldown Lateral con Agarre Inverso (Cable)', 'pulldown-lateral-con-agarre-inverso-cable', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Pullover (Máquina)', 'pullover-maquina', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rack Pull', 'rack-pull', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rear Delt Reverse Fly (Dumbbell)', 'rear-delt-reverse-fly-dumbbell', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rear Kick (Machine)', 'rear-kick-machine', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Alto Iso-Lateral', 'remo-alto-iso-lateral', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Bajo (Suspensión)', 'remo-bajo-suspension', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Bajo Iso-Lateral', 'remo-bajo-iso-lateral', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo con Mancuerna', 'remo-con-mancuerna', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo en Base Rotativa', 'remo-en-base-rotativa', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo en Punta', 'remo-en-punta', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Gorila (Pesa Rusa)', 'remo-gorila-pesa-rusa', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Inclinado (Banda)', 'remo-inclinado-banda', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Inclinado (Barra)', 'remo-inclinado-barra', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Inclinado (Mancuerna)', 'remo-inclinado-mancuerna', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Inclinado con Apoyo de Pecho (Mancuerna)', 'remo-inclinado-con-apoyo-de-pecho-mancuerna', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Invertido', 'remo-invertido', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Iso-Lateral', 'remo-iso-lateral', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Pendlay (Barra)', 'remo-pendlay-barra', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Renegado', 'remo-renegado', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Sentado (Máquina)', 'remo-sentado-maquina', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Sentado con Agarre en V (Cable)', 'remo-sentado-con-agarre-en-v-cable', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Sentado con Cable', 'remo-sentado-con-cable', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Sentado con Cable - Agarre Abierto', 'remo-sentado-con-cable-agarre-abierto', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Vertical (Barra)', 'remo-vertical-barra', 'Hombros', 'Hombros', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remo Vertical (Mancuerna)', 'remo-vertical-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Remos Meadows (Barra)', 'remos-meadows-barra', 'Espalda superior', 'Espalda superior', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Ring Pull Up', 'ring-pull-up', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Ring Push Up', 'ring-push-up', 'Pecho', 'Pecho', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rodillas a Codos', 'rodillas-a-codos', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rodillas al Pecho en Barras Paralelas', 'rodillas-al-pecho-en-barras-paralelas', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rodillo de Antebrazos', 'rodillo-de-antebrazos', 'Antebrazos', 'Antebrazos', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rope Straight Arm Pulldown', 'rope-straight-arm-pulldown', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rotación de Torso', 'rotacion-de-torso', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Rueda Abdominal', 'rueda-abdominal', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Russian Twist (Con Peso Añadido)', 'russian-twist-con-peso-anadido', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Russian Twist (Peso Corporal)', 'russian-twist-peso-corporal', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Salto a la cuerda', 'salto-a-la-cuerda', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Salto al Cajón', 'salto-al-cajon', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Cajón', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Salto al Cajón Lateral', 'salto-al-cajon-lateral', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Cajón', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Saltos de Rana', 'saltos-de-rana', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Senderismo', 'senderismo', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Banda)', 'sentadilla-banda', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Banda', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Barra)', 'sentadilla-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Mancuerna)', 'sentadilla-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Máquina Smith)', 'sentadilla-maquina-smith', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Máquina Smith', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Máquina)', 'sentadilla-maquina', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Peso Corporal)', 'sentadilla-peso-corporal', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla (Suspensión)', 'sentadilla-suspension', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Suspensión', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla a una Pierna', 'sentadilla-a-una-pierna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla al Cajón (Barra)', 'sentadilla-al-cajon-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Búlgara', 'sentadilla-bulgara', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla con Pausa (Barra)', 'sentadilla-con-pausa-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla con Remo', 'sentadilla-con-remo', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla con Salto', 'sentadilla-con-salto', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla de Arranque', 'sentadilla-de-arranque', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Delantera', 'sentadilla-delantera', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla en Pared', 'sentadilla-en-pared', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Goblet', 'sentadilla-goblet', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Goblet con Pesa Rusa', 'sentadilla-goblet-con-pesa-rusa', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Hack', 'sentadilla-hack', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Hack (Máquina)', 'sentadilla-hack-maquina', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Lateral', 'sentadilla-lateral', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Péndulo (Máquina)', 'sentadilla-pendulo-maquina', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Pistol Asistida', 'sentadilla-pistol-asistida', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Profunda', 'sentadilla-profunda', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Sissy (Con Peso)', 'sentadilla-sissy-con-peso', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Split (Mancuerna)', 'sentadilla-split-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Sumo', 'sentadilla-sumo', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Sumo (Barra)', 'sentadilla-sumo-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Sumo (Mancuerna)', 'sentadilla-sumo-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Sumo (Pesa Rusa)', 'sentadilla-sumo-pesa-rusa', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sentadilla Zercher', 'sentadilla-zercher', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sit Up', 'sit-up', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sit Up (Con Peso Añadido)', 'sit-up-con-peso-anadido', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso libre', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Snatch', 'snatch', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Snowboarding', 'snowboarding', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Spiderman', 'spiderman', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Spinning', 'spinning', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Split Jerk', 'split-jerk', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Sprints', 'sprints', 'Cardio', 'Cardio', ARRAY[]::text[], 'Peso corporal', 'cardio', 'time_distance', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Step con Mancuerna', 'step-con-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Step Up', 'step-up', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Straight Arm Lat Pulldown (Cable)', 'straight-arm-lat-pulldown-cable', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Superman', 'superman', 'Espalda baja', 'Espalda baja', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Swing con Pesa Rusa', 'swing-con-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Thruster (Barra)', 'thruster-barra', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Thruster (Pesa Rusa)', 'thruster-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Tirón a la Cara', 'tiron-a-la-cara', 'Hombros', 'Hombros', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Tirón Alto con Pesa Rusa', 'tiron-alto-con-pesa-rusa', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Kettlebell', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Toque de Pies Abdominales', 'toque-de-pies-abdominales', 'Abdominales', 'Abdominales', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Tríceps con Polea', 'triceps-con-polea', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Triceps Pressdown', 'triceps-pressdown', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Triceps Rope Pushdown', 'triceps-rope-pushdown', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Tríceps Sentado', 'triceps-sentado', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Trión con Polea Entre Piernas', 'trion-con-polea-entre-piernas', 'Glúteos', 'Glúteos', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vertical Traction (Machine)', 'vertical-traction-machine', 'Dorsales', 'Dorsales', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vuelos Laterales Sentado (Mancuerna)', 'vuelos-laterales-sentado-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vuelos Posteriores (Cable)', 'vuelos-posteriores-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vuelos Posteriores (Mancuerna)', 'vuelos-posteriores-mancuerna', 'Hombros', 'Hombros', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vuelos Posteriores (Máquina)', 'vuelos-posteriores-maquina', 'Hombros', 'Hombros', ARRAY[]::text[], 'Máquina', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Vuelos Posteriores a Un Brazo (Cable)', 'vuelos-posteriores-a-un-brazo-cable', 'Hombros', 'Hombros', ARRAY[]::text[], 'Cable', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Waiter Curl (Dumbbell)', 'waiter-curl-dumbbell', 'Bíceps', 'Bíceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Wide-Elbow Triceps Press (Dumbbell)', 'wide-elbow-triceps-press-dumbbell', 'Tríceps', 'Tríceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Yoga', 'yoga', 'Cuerpo entero', 'Cuerpo entero', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada', 'zancada', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada (Barra)', 'zancada-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada (Mancuerna)', 'zancada-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada Curtsy (Mancuerna)', 'zancada-curtsy-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada Invertida', 'zancada-invertida', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada Invertida (Barra)', 'zancada-invertida-barra', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Barra', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada Invertida (Mancuerna)', 'zancada-invertida-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancada Lateral', 'zancada-lateral', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancadas Caminando', 'zancadas-caminando', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Peso corporal', 'strength', 'bodyweight', ARRAY[]::text[], 'hevy_style_seed_es', false),
  ('Zancadas Caminando (Mancuerna)', 'zancadas-caminando-mancuerna', 'Cuádriceps', 'Cuádriceps', ARRAY[]::text[], 'Mancuerna', 'strength', 'reps_weight', ARRAY[]::text[], 'hevy_style_seed_es', false)
on conflict (slug) do update set
  name = excluded.name,
  slug = excluded.slug,
  muscle_group = excluded.muscle_group,
  primary_muscle = excluded.primary_muscle,
  equipment = excluded.equipment,
  category = excluded.category,
  tracking_type = excluded.tracking_type,
  source = excluded.source,
  is_custom = excluded.is_custom,
  updated_at = now();
